import type { Metadata } from 'next'
import Link from "next/link";
import { Button } from "./common/components";
import Provider from "./Provider"; // ファイル名は大文字にしないとwarningが出たので
import Header from "./header";
import Main from "./main";
import Footer from "./footer";
//import { Inter } from 'next/font/google'
//import './globals.css'
//const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  //themeColor: "#ffffff",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
    <head />
    <body>
      <Provider>
        <Header />
        <Main>{children}</Main>
        <Footer />
      </Provider>
    </body>
  </html>
  )
}
